project_id = "tisijoiblvcrigwhzprn"

[functions.send-auth-email]
verify_jwt = false

[functions.send-magic-link]
verify_jwt = false

[functions.verify-magic-link]
verify_jwt = false

[functions.notify-new-event]
verify_jwt = false

[functions.notify-balance-change]
verify_jwt = false

[functions.notify-winner]
verify_jwt = false

[functions.notify-referral]
verify_jwt = false

[functions.notify-blog-vote]
verify_jwt = false

[functions.send-admin-email]
verify_jwt = false
